version: '3.8'

services:
  menu_app:
    container_name: menu_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app.env
    command: >
      sh -c "
      echo 'Starting project...' &&
      uvicorn src.main:app --host 0.0.0.0 --reload
      "
    networks:
      - app_network
    ports:
      - "8000:8000"
    depends_on:
      tests:
        condition: service_completed_successfully
      postgres_db:
        condition: service_healthy

  postgres_db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ylab_hw
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 20s
      retries: 100

  tests:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ylab_hw
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    command: >
      sh -c "
      echo 'Making migrations' &&
      alembic upgrade head &&
      echo 'Starting tests' &&
      pytest -vv
      "
    networks:
      - app_network
    depends_on:
      postgres_db:
        condition: service_healthy

networks:
  app_network:

volumes:
  postgres_data:
